server:
  port: 8021

#应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos



        #namespace: public   相同特征的服务进行归类分组管理

        #ephemeral: 默认true(临时实例）当服务宕机 超过心跳 就会将实例剔除掉
        #           false 永久实例   哪怕宕机了也不会删除实例  永远不会删除

        #service: 默认取${spring.application.name} 也可以通过该选配置
        #group: 默认DEFAULT_GROUP 更细的相同特征的服务进行归类分组管理
        #weight: 通常要结合 安装 权重的负载均衡策略， 权重越高分配的流量就越大
        #metadata: version=1 可以结合元数据做扩展
